- include_role:
    name: aws_profile_account
  vars:
    aws_profile_account_role_arn: "arn:aws:iam::{{ aws[aws_account_name].id }}:role/AMIBuilder"
    aws_profile_account_role_session_name: "s3_buckets role"
    aws_profile_account_region: "{{ aws[aws_account_name].region }}"
  when: not profile|default()

- name: set credentials fact
  set_fact:
    sts_creds: "{{ (sts_result|default({})).sts_creds|default({}) }}"
  no_log: yes
  when: not profile|default()

- name: Look for bucket policy file
  set_fact:
    s3_bucket_bucket_policy_json: "{{ lookup('template', item, convert_data=False ) | string }}"
  with_first_found:
    - files:
        - "s3-bucket-policy-{{ bucket_name }}.json"
        - "s3-bucket-policy.json"
      paths:
        - "{{ role_path }}/../../variable_files/s3_buckets"
        - "{{role_path}}/templates"

- name: Create S3 bucket {{ s3_buckets[bucket_name].name }}
  s3_bucket:
    name: "{{ item }}"
    state: present
    policy: "{{ s3_bucket_bucket_policy_json }}"
    region: "{{ s3_buckets[bucket_name].region | default(region) }}"
    profile: "{{ s3_buckets[bucket_name].profile | default(aws_account_name) }}"
    aws_access_key: "{{ (sts_creds|default()).access_key|default(omit) }}"
    aws_secret_key: "{{ (sts_creds|default()).secret_key|default(omit) }}"
    security_token: "{{ (sts_creds|default()).session_token|default(omit) }}"
    versioning: "{{ s3_buckets[bucket_name].versioning | default(True) }}"
  with_items: "{{ s3_buckets[bucket_name].name | default({}) }}"
  register: created_bucket

- set_fact:
    logging_bucket_profile: "{{ s3_buckets[s3_buckets[bucket_name].logging_bucket].profile | default(aws_account_name) }}"
  when: s3_buckets[bucket_name].logging_bucket|default("")

- set_fact:
    logging_bucket_profile: "{{aws_account_name}}"
  when: not s3_buckets[bucket_name].logging_bucket|default("")

- name: Enable bucket logging for {{ s3_buckets[bucket_name].name }}
  s3_logging:
    name: "{{ s3_buckets[bucket_name].name }}"
    profile: "{{ s3_buckets[bucket_name].profile | default(aws_account_name) }}"
    region: "{{ s3_buckets[bucket_name].region | default(region) }}"
    aws_access_key: "{{ (sts_creds|default()).access_key|default(omit) }}"
    aws_secret_key: "{{ (sts_creds|default()).secret_key|default(omit) }}"
    security_token: "{{ (sts_creds|default()).session_token|default(omit) }}"
    target_bucket: "{{ s3_buckets[s3_buckets[bucket_name].logging_bucket].name }}"
    target_prefix: "{{ s3_buckets[bucket_name].logging_prefix }}"
    state: present
  when: s3_buckets[bucket_name].logging_required and s3_buckets[bucket_name].profile | default(aws_account_name)  == logging_bucket_profile

- name: Set bucket lifecycle for {{ s3_buckets[bucket_name].name }}
  s3_lifecycle:
    name: "{{ s3_buckets[bucket_name].name }}"
    profile: "{{ s3_buckets[bucket_name].profile | default(aws_account_name) }}"
    region: "{{ s3_buckets[bucket_name].region | default(region) }}"
    aws_access_key: "{{ (sts_creds|default()).access_key|default(omit) }}"
    aws_secret_key: "{{ (sts_creds|default()).secret_key|default(omit) }}"
    security_token: "{{ (sts_creds|default()).session_token|default(omit) }}"
    transition_days: "{{ item.transition_days|default(omit) }}"
    expiration_days: "{{ item.expiration_days|default(omit) }}"
    prefix: "{{ lifecycle.prefix|default(omit) }}"
    status: enabled
    state: present
  with_items: "{{ s3_buckets[bucket_name].lifecycle }}"
  when: s3_buckets[bucket_name].lifecycle | default()

- block:
    - name: Set fact logging_bucket_events_per_profile_item
      set_fact:
        logging_bucket_events_per_profile_item:
          id: "send-data-to-logstash-{{ item }}"
          prefix: "{{ item }}/"
          events:  ['s3:ObjectCreated:Put']
          lambda_function_arn: "arn:aws:lambda:{{ s3_buckets[bucket_name].region | default(region) }}:{{ aws[s3_buckets[bucket_name].profile|default(aws_account_name)].id }}:function:send-data-to-logstash-from-s3"
      with_items: "{{ aws[s3_buckets[bucket_name].profile|default(aws_account_name)].envs|default({}) }}"
      register: item_result

    - name: Set fact logging_bucket_events_per_profile to be used for bucket event
      set_fact:
        logging_bucket_events_per_profile: "{{ item_result.results | map(attribute='ansible_facts.logging_bucket_events_per_profile_item') | list }}"

    - debug:
        var: logging_bucket_events_per_profile
        verbosity: 2
  when: aws[s3_buckets[bucket_name].profile|default(aws_account_name)].envs|default([])

# Deploy listing_index_page if enable_listing_index_page
- block:
    - name: Get a tempfile
      tempfile:
        state: file
      register: tempfile

    - name: Template the index file
      template:
        src: "list-object-index.html.j2"
        dest: "{{ tempfile.path }}"

    - name: Upload the index.html page for listing object
      aws_s3:
        profile: "{{ profile|default(omit) }}"
        region: "{{ region }}"
        aws_access_key: "{{ (sts_creds|default()).access_key|default(omit) }}"
        aws_secret_key: "{{ (sts_creds|default()).secret_key|default(omit) }}"
        security_token: "{{ (sts_creds|default()).session_token|default(omit) }}"
        bucket: "{{ s3_buckets[bucket_name].name }}"
        mode: put
        object: index.html
        src: "{{ tempfile.path }}"
        metadata: 'Content-Type=text/html'

    - name: Clean up tempfile
      file:
        path: "{{ tempfile.path }}"
        state: absent
  when: s3_buckets[bucket_name].enable_listing_index_page|default()

# Configure website
- name: Enable website
  s3_website:
        profile: "{{ profile|default(omit) }}"
        region: "{{ region }}"
        aws_access_key: "{{ (sts_creds|default()).access_key|default(omit) }}"
        aws_secret_key: "{{ (sts_creds|default()).secret_key|default(omit) }}"
        security_token: "{{ (sts_creds|default()).session_token|default(omit) }}"
        name: "{{ s3_buckets[bucket_name].name }}"
        error_key: "{{ s3_buckets[bucket_name].website.error_key|default(omit) }}"
        redirect_all_requests: "{{ s3_buckets[bucket_name].website.redirect_all_requests|default(omit) }}"
        suffix: "{{ s3_buckets[bucket_name].website.suffix|default(omit) }}"
        state: "{{ s3_buckets[bucket_name].website.state|default('present') }}"
  when: s3_buckets[bucket_name].website|default()
